config/routes.rb
Rails.application.routes.draw do
  resources :boards, only: [:index, :show]
  post '/create_board', to: 'boards#create', as: :create_board

  root 'boards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  validates :email, presence: true, length: { maximum: 50 }
  validates :mines, presence: true
  validates :rows, presence: true
  validates :cols, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  include RandomizeMines

  before_action :board_params, only: [:create]

  attr_accessor :email, :rows, :cols, :mines

  def index
    @boards = Board.order(created_at: :desc).limit(10)
  end

  def create
    byebug
    email = board_params[:email]
    rows = board_params[:rows].to_i
    cols = board_params[:cols].to_i    
    mines = board_params[:mines].to_i

    mines_location = locations(rows, cols, mines)
  
    @board = Board.new(email: email, rows: rows, cols: cols, mines: mines_location)

    if @board.save
      redirect_to @board
    else
      render 'index'
    end
  end

  def show
    begin
      @board = Board.find(params[:id])
      @mines_board = cached_board(@board)
    rescue ActiveRecord::RecordNotFound
      redirect_back_or_to '/'
    end
  end

  private

    def board_params
      params.permit(:email, :rows, :cols, :mines)
    end

    def cached_board(board)
      key = "board#{board.id}"
      Rails.cache.fetch key, expires_in: 1.day do
        grid(board.mines, board.rows, board.cols)
      end
    end

end

app/controllers/concerns/randomize_mines.rb
module RandomizeMines
  extend ActiveSupport::Concern
  def locations(rows = 0, cols = 0, mines = 0)
    dimension = rows * cols

    mines_location = (0..dimension - 1).to_a.sample(mines)
  end

  def neighbours(index, rows, cols)
    neighbours = []
    directions = [-cols - 1, -cols, -cols + 1, -1, 1, cols - 1, cols, cols + 1]
    
    directions.each do |direction|
      neighbour_index = index + direction
      if neighbour_index >= 0 && neighbour_index < rows * cols &&
         !((index % cols) == 0 && (direction == -1 || direction == (cols - 1) || direction == (-cols - 1))) && 
         !((index % cols) == (cols - 1) && (direction == 1 || direction == (-cols + 1) || direction == (cols + 1)))
        neighbours << neighbour_index
      end
    end
    
    neighbours.uniq
  end

  def grid(mines, rows = 0, cols = 0)
    grid = Array.new(rows).map {|_| Array.new(cols)}

    mines_hash = mines.product([true]).to_h

    rows.times do |r|
      cols.times do |c|
        index = r * cols + c
        if mines_hash[index]
          grid[r][c] = -1
        else
          neighs = neighbours(index, rows, cols)
          grid[r][c] = mines_hash.values_at(*neighs).compact.size
        end
      end
    end

    grid
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  def show_button(value)
    bg = 'background'+ value.to_s
    content_tag(:button, "", class: "button #{bg} border")
  end
end

app/views/boards/401.html.erb
  <div class="error-container">
    <div class="error-box">
      <div class="error-code">401</div>
      <div class="error-message">Unauthorized Access</div>
      <p>You are not authorized to view this page. Please log in or contact the administrator for assistance.</p>
    </div>
  </div>

app/views/boards/index.html.erb
<div class="container">
  <div class="row p-5 align-items-stretch">
    <div class="col-4 p-4 m-2 border">
      <h2>Create a new Board</h2>
      <%= form_with(url: create_board_path, method: :post, local: true) do |form| %>
        <div class="mb-3 form-group">
          <%= form.label :query, "Email : ", class: 'form-label' %>
          <%= form.email_field :email, class: 'form-control', required: true %>
        </div>

        <div class="mb-3 form-group">
          <%= form.label :query, "Rows : ", class: 'form-label' %>
          <%= form.number_field :rows, class: 'form-control', required: true, min: 1 %>
        </div>

        <div class="mb-3 form-group">
          <%= form.label :query, "Columns : ", class: 'form-label' %>
          <%= form.number_field :cols, class: 'form-control', required: true, min: 1 %>
        </div>

        <div class="mb-3 form-group">
          <%= form.label :query, "Mines : ", class: 'form-label' %>
          <%= form.number_field :mines, class: 'form-control', required: true, min: 1 %>
        </div>

        <%= form.submit "Generate Board", class: 'btn btn-primary' %>
      <% end %>
      </div>
      <div class="col-7 p-4 m-2 border">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Email</th>
              <th scope="col">Rows</th>
              <th scope="col">Cols</th>
              <th scope="col">Mines</th>
              <th scope="col">Board</th>
            </tr>
          </thead>
          <tbody>
            <% @boards.each_with_index do |board, index| %>
              <tr>
                <th scope="row"><%= index + 1 %></th>
                <td><%= board.email %></td>
                <td><%= board.rows %></td>
                <td><%= board.cols %></td>
                <td><%= board.mines.count %></td>
                <td><%= link_to "Show",board %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class = "container">
  <div class="p-5 m-10 border">
    <table class="table">
      <thead>
        <tr>
          <th scope="row">Board Details</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Email</th>
          <td><%=@board.email%></td>
        </tr>
        <tr>
          <th scope="row">No. of Columns</th>
          <td><%=@board.cols%></td>
        </tr>
        <tr>
          <th scope="row">No. of Rows</th>
          <td><%=@board.rows%></td>
        </tr>
            <tr>
          <th scope="row">No. of Mines</th>
          <td><%=@board.mines.count%></td>
        </tr>
      </tbody>
    </table>
    <div class = "d-flex flex-column scroll align-items-center">
      <% @board.rows.times do |r| %>
        <div class="inline">
          <% @board.cols.times do |c| %>
            <%= show_button(@mines_board[r][c])%>
          <% end %>
        </div>
      <% end %>
    </div>
    <div>
      <%= link_to 'Back', boards_path(), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>